using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CharacterController : MonoBehaviour
{
    [SerializeField] GameObject cameraHolder;
    [SerializeField] float sprintSpeed, walkSpeed, jumpForce, smoothTime, MinY, MaxY;

    public float currentSpeed;

    private Rigidbody rb;
    bool grounded;

    Vector3 smoothMoveVelocity;
    Vector3 moveAmount;

    Vector2 _mouseAbsolute;
    Vector2 _smoothMouse;

    public Vector2 clampInDegrees = new Vector2(360, 180);
    public Vector2 sensitivity = new Vector2(2, 2);
    public Vector2 smoothing = new Vector2(3, 3);
    public Vector2 targetDirection;
    public Vector2 targetCharacterDirection;

    void Awake()
    {
        rb = GetComponent<Rigidbody>();
        targetDirection = transform.localRotation.eulerAngles;
    }

    void Start()
    {
        Cursor.lockState = CursorLockMode.Locked;    
    }

    // Update is called once per frame
    void Update()
    {
        Look();
        Move();
        Jump();
    }

    void Move()
    {
        Vector3 moveDir = new Vector3(Input.GetAxisRaw("Horizontal"), 0, Input.GetAxisRaw("Vertical")).normalized;

        currentSpeed = Input.GetKey(KeyCode.LeftShift) ? sprintSpeed : walkSpeed;

        moveAmount = Vector3.SmoothDamp(moveAmount, moveDir * (Input.GetKey(KeyCode.LeftShift) ? sprintSpeed : walkSpeed), ref smoothMoveVelocity, smoothTime);
    }

    void Look()
    {
        // TODO: ton code de cam√©ra ici
    }

    void Jump()
    {
        // TODO: ton code de saut ici
    }
}
